/* AUTO-GENERATED by tools/gen_satellites.py — do not edit by hand.
 *
 * Refreshed 2026-05-08 from CelesTrak's GP query API:
 *   https://celestrak.org/NORAD/elements/gp.php?CATNR=<n>&FORMAT=TLE
 *
 * The voidwatch source code wrapping this catalog is MIT-licensed (see
 * LICENSE in the repo root). The TLE numbers themselves are factual
 * data derived from US Space Force tracking and republished by
 * CelesTrak. CelesTrak does not assert copyright on the numbers but
 * requests attribution for redistributors — voidwatch credits CelesTrak
 * in CITATIONS.md and THIRD_PARTY_LICENSES.md.
 *
 * TLEs decay in days. voidwatch's stale-policy in src/satellite.c
 * (and AstroState's render gating) dims at >7d, hides at >14d, and
 * refuses propagation at >30d. Refresh by rerunning the generator.
 *
 * Every entry must be near-Earth (mean motion > 6.4 rev/day, period
 * < 225 min) — deep-space SDP4 is deferred. The generator validates
 * this; if a future entry trips the check, it bails rather than
 * silently emitting a TLE that voidwatch would refuse at runtime.
 */

#include "satellite.h"

const SatelliteElements satellite_elements[SATELLITE_COUNT] = {
    /* International Space Station — the canonical visible-pass target */
    {
        .name    = "ISS (ZARYA)",
        .line1   = "1 25544U 98067A   26128.19937109  .00004920  00000+0  96926-4 0  9998",
        .line2   = "2 25544  51.6308 138.0417 0007476  35.9089 324.2400 15.49139257565554",
        .aliases = "iss,zarya,25544",
        .catalog = 25544,
    },
    /* Hubble Space Telescope */
    {
        .name    = "HST",
        .line1   = "1 20580U 90037B   26127.97667409  .00005999  00000+0  19110-3 0  9996",
        .line2   = "2 20580  28.4762 355.2958 0002157  58.4789 301.6018 15.30319964782400",
        .aliases = "hst,hubble,20580",
        .catalog = 20580,
    },
    /* NOAA 19 — polar weather satellite, reliable LEO sun-synchronous */
    {
        .name    = "NOAA 19",
        .line1   = "1 33591U 09005A   26128.26774666  .00000018  00000+0  33300-4 0  9999",
        .line2   = "2 33591  98.9529 199.1109 0014524 140.2237 220.0003 14.13467775888848",
        .aliases = "noaa,noaa19,noaa-19,33591",
        .catalog = 33591,
    },
    /* CSS Tianhe — Chinese space station core module */
    {
        .name    = "CSS (TIANHE)",
        .line1   = "1 48274U 21035A   26128.23670278  .00021140  00000+0  22512-3 0  9992",
        .line2   = "2 48274  41.4663 205.0585 0004840 355.4513   4.6282 15.63470026286921",
        .aliases = "css,tianhe,tiangong,48274",
        .catalog = 48274,
    },
};
const int satellite_count = SATELLITE_COUNT;
